### ISSUE TITLE
0 ERROR: Not all column names specified.

### ISSUE THREAD

**Issue by chinnyy** [cgrace1978/manhheatmap#13]
Hello! 

I am trying to run the gen_snpfile.pl to generate the input snp file, however, I keep getting the error "0 ERROR: Not all column names specified." even though I filled in the required parameters and the column name matches that of the GWAS file.

The specified parameters are listed below:

Parameters:
  GWAS Filename: gwasfile.txt
  Variant column name: var
  Variant chromosome column name: chrom
  Variant position column name: pos
  Variant beta column name: beta
  Variant allele frequency column name: eaf
  Variant pvalue column name: pval
  GWAS threshold: 5e-08
  Gene database to use: glist-hg38.txt
  Distance between 2 loci: 500000
  Max. distance between variant and gene to consider: 500000
  Output file: snpfile_out.txt

Thank you!

**Comment by cgrace1978** [comment]
Hi,

Can you send the me the command line that you used to run the perl script.

Thanks,

Chris

**Comment by chinnyy** [comment]
Hello,

Here is the command line:
perl gen_snpfile.pl --gwasfile gwasfile.txt --chrom chrom --var var --pos pos --pval pval --beta beta --eaf eaf --genefile glist-hg38.txt --out snpfile_out

Regards,
Faith

**Comment by cgrace1978** [comment]
Please check the header file of gwasfile.txt, the error message means that the column names you specified do not match.

i.e. your header should be:
chrom   var     pos     pval    beta    eaf

Thanks,

Chris

**Comment by chinnyy** [comment]
I checked my gwasfile.txt file but my header matches to what i keyed into the command line, here is an example of how my first 5 rows look like 

"chrom"	"var"	"pos"	"pval"	"beta"	"eaf"
1	"MantaINS:10:0:0:0:1:0"	54715	1	NA	NA
1	"MantaINS:7:0:0:0:0:0"	99039	1	NA	NA
1	"MantaINS:1:0:0:0:7:0"	99042	1	NA	NA
1	"MantaINS:1:0:0:0:0:0"	99069	1	NA	NA

Thank you!
Warm regards,
Faith

**Comment by cgrace1978** [comment]
The files needs to be tab delimited, and you should remove the quotations. So like this:
chrom	var	pos	pval	beta	eaf
1	MantaINS:10:0:0:0:1:0	54715	1	NA	NA
1	MantaINS:7:0:0:0:0:0	99039	1	NA	NA
1	MantaINS:1:0:0:0:7:0	99042	1	NA	NA
1	MantaINS:1:0:0:0:0:0	99069	1	NA	NA

**Comment by chinnyy** [comment]
I removed the quotations but the same error still comes up:

Parameters:
  GWAS Filename: gwasfile.txt
  Variant column name: var
  Variant chromosome column name: chrom
  Variant position column name: pos
  Variant beta column name: beta
  Variant allele frequency column name: eaf
  Variant pvalue column name: pval
  GWAS threshold: 5e-08
  Gene database to use: glist-hg38.txt
  Distance between 2 loci: 500000
  Max. distance between variant and gene to consider: 500000
  Output file: snpfile_out.txt

5 ERROR: Not all column names specified. Please use --help for usage.

**Comment by cgrace1978** [comment]
Can you attach the header of the file you are trying to use?

**Comment by chinnyy** [comment]
Hello! It looks like this now

chrom	var	pos	pval	beta	eaf
1	MantaINS:10:0:0:0:1:0	54715	1	NA	NA
1	MantaINS:7:0:0:0:0:0	99039	1	NA	NA
1	MantaINS:1:0:0:0:7:0	99042	1	NA	NA
1	MantaINS:1:0:0:0:0:0	99069	1	NA	NA

Here is the .txt file if it is easier to see
[gwasfile.txt](https://github.com/cgrace1978/manhplot/files/14045675/gwasfile.txt)

**Comment by cgrace1978** [comment]
Please run dos2unix command on the file.

**Comment by chinnyy** [comment]
It works now. Thank you so much!
